name: systemd_gen
description: A systemd unit generator for Dart.
version: 2.0.0
author: Pavel Snitko <brian57reg@gmail.com>
homepage: https://github.com/PavelS0/
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0
  
dev_dependencies:
  test: ^1.16.0
